import Head from 'next/head';
import React from 'react';
import Navigation from '../Navigation';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>n-News</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Navigation />
                {children}
            </div>
        </>
    );
}

export default Layout;
